In [27]:
# в дальнейшем под матрицей подразумевается двумерный массив

In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 11, 14, 124, 533, 5315]) # создаем массив из элементов списка
print(arr)


[   1    2    3    4   11   14  124  533 5315]


In [29]:
a = np.arange(10) # создаем массив из элементов последовательности целых чисел от 0 до 9
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
matrix_of_ones = np.ones((3, 5)) # создаем матрицу из единиц размером 3х5
print(matrix_of_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
matrix_of_zeros = np.zeros((10, 10)) # создаем матрицу 10х10 состоящую из нулей
print(matrix_of_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
b = np.array(([56, 33, 11], [53, 22, 99]))
print(b)
print() # перенос строки вывода 
print(np.shape(b)) # выводим форму массива и видим, что он двумерный, сост. из 2х строк и 3х столбцов 

[[56 33 11]
 [53 22 99]]

(2, 3)


In [33]:
floats = np.array([1.4, 44.2, 41.111, 143.08]) # создаем массив из списка чисел с плавающей точкой
integers = np.array([1, 3, 5, 234, 124, 5666]) # создаем массив из списка целых чисел
print(floats.dtype) # выводим тип элементов массива floats
print(integers.dtype) # выводим тип элементов массива integers

float64
int64


In [34]:
random_arr = np.array(([1, 2, 3, 4], [5, 6, 7, 8]))
element_1 = random_arr[1][2] # получаем элемент, стоящий во второй строке третьим
element_2 = random_arr[0, 3] # получаем элемент, стоящий в первой строке четвертым
part_of_arr_1 = random_arr[1][:3] # получаем подмассив из элементов второй строки до четвертого элемента
part_of_arr_2 = random_arr[0][::-1] # получаем подмассив из элементов первой строки расположенных в обратном порядке
print(element_1)
print(element_2)
print(part_of_arr_1)
print(part_of_arr_2)

7
4
[5 6 7]
[4 3 2 1]


In [35]:
matrix_a = np.array(([1, 2, 3], [3, 4, 5], [13, 4, 2]))
matrix_b = np.array(([5, 6, 7], [7, 8, 9], [11, 12, 13]))
addition = matrix_a + matrix_b # поэлементное сложение массивов
subtraction = matrix_a - matrix_b # вычитание из элементов первого массива соотв. элементов второго
multiplication = matrix_a * matrix_b # перемножение двух массивов
middle_ariphmetical_a = np.mean(matrix_a)
print(addition)
print()
print(subtraction)
print()
print(multiplication)
print()
print(middle_ariphmetical_a)

[[ 6  8 10]
 [10 12 14]
 [24 16 15]]

[[ -4  -4  -4]
 [ -4  -4  -4]
 [  2  -8 -11]]

[[  5  12  21]
 [ 21  32  45]
 [143  48  26]]

4.111111111111111
